version: "3.9"
services:
  website:
    build: .
    depends_on:
      - database
    volumes:
      - "./config.ini:/opt/app/config.ini"
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: ch@ng3me
      DJANGO_SUPERUSER_EMAIL: me@example.com
    ports:
      - "8080:8080"

  database:
    image: postgres:alpine
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: dJ5nG0_cH@nG3mE

volumes:
  postgres-data:
