# Generated by Django 4.1.6 on 2023-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('service', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyStateCode',
            fields=[
                ('state_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
