# Generated by Django 4.1.7 on 2023-03-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_alter_oauthtoken_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempStateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=32)),
                ('state_code', models.CharField(max_length=16)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='SpotifyStateCode',
        ),
        migrations.AddConstraint(
            model_name='tempstatecode',
            constraint=models.UniqueConstraint(fields=('domain', 'state_code'), name='unique_domain_state'),
        ),
    ]
